version: "3.1"

services:
  fkj-schedule-web-prod:
    image: nginx:1.13.0
    ports:
      - 7006:80
    container_name: "fkj-schedule-web-prod"
    volumes:
      - ../dist:/usr/share/nginx/html/LK-0200024/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
